"""
Constellation related constants. Sourced from GUI and from installation base.
"""

# Transaction Related Constants
TRANSACTION_LINE_STYLE_DASHED = "DASHED"
TRANSACTION_LINE_STYLE_DIAMOND = "DIAMOND"
TRANSACTION_LINE_STYLE_DOTTED = "DOTTED"
TRANSACTION_LINE_STYLE_SOLID = "SOLID"

TRANSACTION_TYPE_BEHAVIOR = "Behavior"
TRANSACTION_TYPE_COMMUNICATION = "Communication"
TRANSACTION_TYPE_CORRELATION = "Correlation"
TRANSACTION_TYPE_CREATED = "Created"
TRANSACTION_TYPE_LOCATION = "Location"
TRANSACTION_TYPE_NETWORK = "Network"
TRANSACTION_TYPE_REFERENCED = "Referenced"
TRANSACTION_TYPE_RELATIONSHIP = "Relationship"
TRANSACTION_TYPE_SIMILARITY = "Similarity"
TRANSACTION_TYPE_UNKNOWN = "Unknown"
